(define (problem prob) (:domain alignment)
	(:objects
		

		s0_4 s0_16 s0_11 s0_6 s0_10 s0_15 s0_13 s0_14 s0_8 s0_5 
		s0_0 s0_3 s0_9 s0_7 s0_17 s0_12 s0_2 s0_1 s0_dummy - petrinet_state

		s10 s11 s12 s20 s21 s22 s23 s40 s41 s42 
		s60 s61 s62 s70 s71 s72 - automaton_state

		activitya activityb activitye activityf activityc activityd activityi activityj activityg activityh 
		activitym activityn activityk activityl activityq activityr activityo activityp activitys activityt 
		- activity

		existence_activityb precedence_activityf_activityo response_activityg_activityp 
		not_response_activityl_activityl chain_response_activitya_activityc absence_activityk 
		response_activityn_activityt - constraint
)
	(:init 
		(= (total-cost) 0)
		(recovery_finished)

		;Petri Net automaton:
		(cur_state s0_0)
		(init_state s0_0)
		(dummy_state s0_dummy)
		(final_state s0_12)
		(final_state s0_dummy)
		(automaton s0_0 activitya s0_1)
		(automaton s0_0 activityb s0_dummy)
		(automaton s0_0 activitye s0_dummy)
		(automaton s0_0 activityf s0_dummy)
		(automaton s0_0 activityc s0_dummy)
		(automaton s0_0 activityd s0_dummy)
		(automaton s0_0 activityi s0_dummy)
		(automaton s0_0 activityj s0_dummy)
		(automaton s0_0 activityg s0_dummy)
		(automaton s0_0 activityh s0_dummy)
		(automaton s0_0 activitym s0_dummy)
		(automaton s0_0 activityn s0_dummy)
		(automaton s0_0 activityk s0_dummy)
		(automaton s0_0 activityl s0_dummy)
		(automaton s0_0 activityq s0_dummy)
		(automaton s0_0 activityr s0_dummy)
		(automaton s0_0 activityo s0_dummy)
		(automaton s0_0 activityp s0_dummy)
		(automaton s0_0 activitys s0_dummy)
		(automaton s0_0 activityt s0_dummy)
		(automaton s0_1 activityg s0_2)
		(automaton s0_1 activitya s0_dummy)
		(automaton s0_1 activityb s0_dummy)
		(automaton s0_1 activitye s0_dummy)
		(automaton s0_1 activityf s0_dummy)
		(automaton s0_1 activityd s0_dummy)
		(automaton s0_1 activityi s0_dummy)
		(automaton s0_1 activityj s0_dummy)
		(automaton s0_1 activityh s0_dummy)
		(automaton s0_1 activitym s0_dummy)
		(automaton s0_1 activityn s0_dummy)
		(automaton s0_1 activityk s0_dummy)
		(automaton s0_1 activityl s0_dummy)
		(automaton s0_1 activityq s0_dummy)
		(automaton s0_1 activityr s0_dummy)
		(automaton s0_1 activityo s0_dummy)
		(automaton s0_1 activityp s0_dummy)
		(automaton s0_1 activitys s0_dummy)
		(automaton s0_1 activityt s0_dummy)
		(automaton s0_2 activityi s0_3)
		(automaton s0_2 activitya s0_dummy)
		(automaton s0_2 activityb s0_dummy)
		(automaton s0_2 activitye s0_dummy)
		(automaton s0_2 activityf s0_dummy)
		(automaton s0_2 activityc s0_dummy)
		(automaton s0_2 activityd s0_dummy)
		(automaton s0_2 activityj s0_dummy)
		(automaton s0_2 activityg s0_dummy)
		(automaton s0_2 activityh s0_dummy)
		(automaton s0_2 activitym s0_dummy)
		(automaton s0_2 activityn s0_dummy)
		(automaton s0_2 activityk s0_dummy)
		(automaton s0_2 activityl s0_dummy)
		(automaton s0_2 activityq s0_dummy)
		(automaton s0_2 activityr s0_dummy)
		(automaton s0_2 activityo s0_dummy)
		(automaton s0_2 activityp s0_dummy)
		(automaton s0_2 activitys s0_dummy)
		(automaton s0_2 activityt s0_dummy)
		(automaton s0_3 activityj s0_4)
		(automaton s0_3 activitya s0_dummy)
		(automaton s0_3 activityb s0_dummy)
		(automaton s0_3 activitye s0_dummy)
		(automaton s0_3 activityf s0_dummy)
		(automaton s0_3 activityc s0_dummy)
		(automaton s0_3 activityd s0_dummy)
		(automaton s0_3 activityi s0_dummy)
		(automaton s0_3 activityg s0_dummy)
		(automaton s0_3 activityh s0_dummy)
		(automaton s0_3 activitym s0_dummy)
		(automaton s0_3 activityn s0_dummy)
		(automaton s0_3 activityk s0_dummy)
		(automaton s0_3 activityl s0_dummy)
		(automaton s0_3 activityq s0_dummy)
		(automaton s0_3 activityr s0_dummy)
		(automaton s0_3 activityo s0_dummy)
		(automaton s0_3 activityp s0_dummy)
		(automaton s0_3 activitys s0_dummy)
		(automaton s0_3 activityt s0_dummy)
		(automaton s0_4 activityh s0_5)
		(automaton s0_4 activitya s0_dummy)
		(automaton s0_4 activityb s0_dummy)
		(automaton s0_4 activitye s0_dummy)
		(automaton s0_4 activityf s0_dummy)
		(automaton s0_4 activityc s0_dummy)
		(automaton s0_4 activityd s0_dummy)
		(automaton s0_4 activityi s0_dummy)
		(automaton s0_4 activityj s0_dummy)
		(automaton s0_4 activityg s0_dummy)
		(automaton s0_4 activitym s0_dummy)
		(automaton s0_4 activityn s0_dummy)
		(automaton s0_4 activityl s0_dummy)
		(automaton s0_4 activityq s0_dummy)
		(automaton s0_4 activityr s0_dummy)
		(automaton s0_4 activityo s0_dummy)
		(automaton s0_4 activityp s0_dummy)
		(automaton s0_4 activitys s0_dummy)
		(automaton s0_4 activityt s0_dummy)
		(automaton s0_5 activityb s0_6)
		(automaton s0_5 activitya s0_dummy)
		(automaton s0_5 activitye s0_dummy)
		(automaton s0_5 activityf s0_dummy)
		(automaton s0_5 activityc s0_dummy)
		(automaton s0_5 activityd s0_dummy)
		(automaton s0_5 activityi s0_dummy)
		(automaton s0_5 activityj s0_dummy)
		(automaton s0_5 activityg s0_dummy)
		(automaton s0_5 activityh s0_dummy)
		(automaton s0_5 activitym s0_dummy)
		(automaton s0_5 activityn s0_dummy)
		(automaton s0_5 activityk s0_dummy)
		(automaton s0_5 activityl s0_dummy)
		(automaton s0_5 activityq s0_dummy)
		(automaton s0_5 activityr s0_dummy)
		(automaton s0_5 activityo s0_dummy)
		(automaton s0_5 activityp s0_dummy)
		(automaton s0_5 activitys s0_dummy)
		(automaton s0_5 activityt s0_dummy)
		(automaton s0_6 activitym s0_7)
		(automaton s0_6 activitya s0_dummy)
		(automaton s0_6 activityb s0_dummy)
		(automaton s0_6 activitye s0_dummy)
		(automaton s0_6 activityf s0_dummy)
		(automaton s0_6 activityc s0_dummy)
		(automaton s0_6 activityd s0_dummy)
		(automaton s0_6 activityi s0_dummy)
		(automaton s0_6 activityj s0_dummy)
		(automaton s0_6 activityg s0_dummy)
		(automaton s0_6 activityh s0_dummy)
		(automaton s0_6 activityn s0_dummy)
		(automaton s0_6 activityk s0_dummy)
		(automaton s0_6 activityl s0_dummy)
		(automaton s0_6 activityq s0_dummy)
		(automaton s0_6 activityr s0_dummy)
		(automaton s0_6 activityo s0_dummy)
		(automaton s0_6 activityp s0_dummy)
		(automaton s0_6 activitys s0_dummy)
		(automaton s0_6 activityt s0_dummy)
		(automaton s0_7 activityo s0_8)
		(automaton s0_7 activitya s0_dummy)
		(automaton s0_7 activityb s0_dummy)
		(automaton s0_7 activitye s0_dummy)
		(automaton s0_7 activityf s0_dummy)
		(automaton s0_7 activityc s0_dummy)
		(automaton s0_7 activityd s0_dummy)
		(automaton s0_7 activityi s0_dummy)
		(automaton s0_7 activityj s0_dummy)
		(automaton s0_7 activityg s0_dummy)
		(automaton s0_7 activityh s0_dummy)
		(automaton s0_7 activitym s0_dummy)
		(automaton s0_7 activityn s0_dummy)
		(automaton s0_7 activityk s0_dummy)
		(automaton s0_7 activityl s0_dummy)
		(automaton s0_7 activityq s0_dummy)
		(automaton s0_7 activityr s0_dummy)
		(automaton s0_7 activitys s0_dummy)
		(automaton s0_7 activityt s0_dummy)
		(automaton s0_8 activityn s0_9)
		(automaton s0_8 activitya s0_dummy)
		(automaton s0_8 activityb s0_dummy)
		(automaton s0_8 activitye s0_dummy)
		(automaton s0_8 activityf s0_dummy)
		(automaton s0_8 activityc s0_dummy)
		(automaton s0_8 activityd s0_dummy)
		(automaton s0_8 activityi s0_dummy)
		(automaton s0_8 activityj s0_dummy)
		(automaton s0_8 activityg s0_dummy)
		(automaton s0_8 activityh s0_dummy)
		(automaton s0_8 activitym s0_dummy)
		(automaton s0_8 activityk s0_dummy)
		(automaton s0_8 activityl s0_dummy)
		(automaton s0_8 activityq s0_dummy)
		(automaton s0_8 activityr s0_dummy)
		(automaton s0_8 activityo s0_dummy)
		(automaton s0_8 activityp s0_dummy)
		(automaton s0_8 activitys s0_dummy)
		(automaton s0_8 activityt s0_dummy)
		(automaton s0_9 activityr s0_10)
		(automaton s0_9 activitya s0_dummy)
		(automaton s0_9 activityb s0_dummy)
		(automaton s0_9 activitye s0_dummy)
		(automaton s0_9 activityf s0_dummy)
		(automaton s0_9 activityc s0_dummy)
		(automaton s0_9 activityd s0_dummy)
		(automaton s0_9 activityi s0_dummy)
		(automaton s0_9 activityj s0_dummy)
		(automaton s0_9 activityg s0_dummy)
		(automaton s0_9 activityh s0_dummy)
		(automaton s0_9 activitym s0_dummy)
		(automaton s0_9 activityn s0_dummy)
		(automaton s0_9 activityk s0_dummy)
		(automaton s0_9 activityl s0_dummy)
		(automaton s0_9 activityq s0_dummy)
		(automaton s0_9 activityo s0_dummy)
		(automaton s0_9 activityp s0_dummy)
		(automaton s0_9 activitys s0_dummy)
		(automaton s0_9 activityt s0_dummy)
		(automaton s0_10 activitys s0_11)
		(automaton s0_10 activitya s0_dummy)
		(automaton s0_10 activityb s0_dummy)
		(automaton s0_10 activitye s0_dummy)
		(automaton s0_10 activityf s0_dummy)
		(automaton s0_10 activityc s0_dummy)
		(automaton s0_10 activityd s0_dummy)
		(automaton s0_10 activityi s0_dummy)
		(automaton s0_10 activityj s0_dummy)
		(automaton s0_10 activityg s0_dummy)
		(automaton s0_10 activityh s0_dummy)
		(automaton s0_10 activitym s0_dummy)
		(automaton s0_10 activityn s0_dummy)
		(automaton s0_10 activityk s0_dummy)
		(automaton s0_10 activityl s0_dummy)
		(automaton s0_10 activityq s0_dummy)
		(automaton s0_10 activityr s0_dummy)
		(automaton s0_10 activityo s0_dummy)
		(automaton s0_10 activityp s0_dummy)
		(automaton s0_10 activityt s0_dummy)
		(automaton s0_11 activityt s0_12)
		(automaton s0_11 activitya s0_dummy)
		(automaton s0_11 activityb s0_dummy)
		(automaton s0_11 activitye s0_dummy)
		(automaton s0_11 activityf s0_dummy)
		(automaton s0_11 activityc s0_dummy)
		(automaton s0_11 activityd s0_dummy)
		(automaton s0_11 activityi s0_dummy)
		(automaton s0_11 activityj s0_dummy)
		(automaton s0_11 activityg s0_dummy)
		(automaton s0_11 activityh s0_dummy)
		(automaton s0_11 activitym s0_dummy)
		(automaton s0_11 activityn s0_dummy)
		(automaton s0_11 activityk s0_dummy)
		(automaton s0_11 activityl s0_dummy)
		(automaton s0_11 activityq s0_dummy)
		(automaton s0_11 activityr s0_dummy)
		(automaton s0_11 activityo s0_dummy)
		(automaton s0_11 activityp s0_dummy)
		(automaton s0_11 activitys s0_dummy)
		(automaton s0_7 activityp s0_13)
		(automaton s0_13 activityq s0_8)
		(automaton s0_13 activitya s0_dummy)
		(automaton s0_13 activityb s0_dummy)
		(automaton s0_13 activitye s0_dummy)
		(automaton s0_13 activityf s0_dummy)
		(automaton s0_13 activityc s0_dummy)
		(automaton s0_13 activityd s0_dummy)
		(automaton s0_13 activityi s0_dummy)
		(automaton s0_13 activityj s0_dummy)
		(automaton s0_13 activityg s0_dummy)
		(automaton s0_13 activityh s0_dummy)
		(automaton s0_13 activitym s0_dummy)
		(automaton s0_13 activityn s0_dummy)
		(automaton s0_13 activityk s0_dummy)
		(automaton s0_13 activityl s0_dummy)
		(automaton s0_13 activityr s0_dummy)
		(automaton s0_13 activityo s0_dummy)
		(automaton s0_13 activityp s0_dummy)
		(automaton s0_13 activitys s0_dummy)
		(automaton s0_13 activityt s0_dummy)
		(automaton s0_4 activityk s0_14)
		(automaton s0_14 activityl s0_2)
		(automaton s0_14 activitya s0_dummy)
		(automaton s0_14 activityb s0_dummy)
		(automaton s0_14 activitye s0_dummy)
		(automaton s0_14 activityf s0_dummy)
		(automaton s0_14 activityc s0_dummy)
		(automaton s0_14 activityd s0_dummy)
		(automaton s0_14 activityi s0_dummy)
		(automaton s0_14 activityj s0_dummy)
		(automaton s0_14 activityg s0_dummy)
		(automaton s0_14 activityh s0_dummy)
		(automaton s0_14 activitym s0_dummy)
		(automaton s0_14 activityn s0_dummy)
		(automaton s0_14 activityk s0_dummy)
		(automaton s0_14 activityq s0_dummy)
		(automaton s0_14 activityr s0_dummy)
		(automaton s0_14 activityo s0_dummy)
		(automaton s0_14 activityp s0_dummy)
		(automaton s0_14 activitys s0_dummy)
		(automaton s0_14 activityt s0_dummy)
		(automaton s0_1 activityc s0_15)
		(automaton s0_15 activityd s0_16)
		(automaton s0_15 activitya s0_dummy)
		(automaton s0_15 activityb s0_dummy)
		(automaton s0_15 activitye s0_dummy)
		(automaton s0_15 activityf s0_dummy)
		(automaton s0_15 activityc s0_dummy)
		(automaton s0_15 activityi s0_dummy)
		(automaton s0_15 activityj s0_dummy)
		(automaton s0_15 activityg s0_dummy)
		(automaton s0_15 activityh s0_dummy)
		(automaton s0_15 activitym s0_dummy)
		(automaton s0_15 activityn s0_dummy)
		(automaton s0_15 activityk s0_dummy)
		(automaton s0_15 activityl s0_dummy)
		(automaton s0_15 activityq s0_dummy)
		(automaton s0_15 activityr s0_dummy)
		(automaton s0_15 activityo s0_dummy)
		(automaton s0_15 activityp s0_dummy)
		(automaton s0_15 activitys s0_dummy)
		(automaton s0_15 activityt s0_dummy)
		(automaton s0_16 activitye s0_17)
		(automaton s0_16 activitya s0_dummy)
		(automaton s0_16 activityb s0_dummy)
		(automaton s0_16 activityf s0_dummy)
		(automaton s0_16 activityc s0_dummy)
		(automaton s0_16 activityd s0_dummy)
		(automaton s0_16 activityi s0_dummy)
		(automaton s0_16 activityj s0_dummy)
		(automaton s0_16 activityg s0_dummy)
		(automaton s0_16 activityh s0_dummy)
		(automaton s0_16 activitym s0_dummy)
		(automaton s0_16 activityn s0_dummy)
		(automaton s0_16 activityk s0_dummy)
		(automaton s0_16 activityl s0_dummy)
		(automaton s0_16 activityq s0_dummy)
		(automaton s0_16 activityr s0_dummy)
		(automaton s0_16 activityo s0_dummy)
		(automaton s0_16 activityp s0_dummy)
		(automaton s0_16 activitys s0_dummy)
		(automaton s0_16 activityt s0_dummy)
		(automaton s0_17 activityf s0_5)
		(automaton s0_17 activitya s0_dummy)
		(automaton s0_17 activityb s0_dummy)
		(automaton s0_17 activitye s0_dummy)
		(automaton s0_17 activityc s0_dummy)
		(automaton s0_17 activityd s0_dummy)
		(automaton s0_17 activityi s0_dummy)
		(automaton s0_17 activityj s0_dummy)
		(automaton s0_17 activityg s0_dummy)
		(automaton s0_17 activityh s0_dummy)
		(automaton s0_17 activitym s0_dummy)
		(automaton s0_17 activityn s0_dummy)
		(automaton s0_17 activityk s0_dummy)
		(automaton s0_17 activityl s0_dummy)
		(automaton s0_17 activityq s0_dummy)
		(automaton s0_17 activityr s0_dummy)
		(automaton s0_17 activityo s0_dummy)
		(automaton s0_17 activityp s0_dummy)
		(automaton s0_17 activitys s0_dummy)
		(automaton s0_17 activityt s0_dummy)
		(automaton s0_12 activitya s0_dummy)
		(automaton s0_12 activityb s0_dummy)
		(automaton s0_12 activitye s0_dummy)
		(automaton s0_12 activityf s0_dummy)
		(automaton s0_12 activityc s0_dummy)
		(automaton s0_12 activityd s0_dummy)
		(automaton s0_12 activityi s0_dummy)
		(automaton s0_12 activityj s0_dummy)
		(automaton s0_12 activityg s0_dummy)
		(automaton s0_12 activityh s0_dummy)
		(automaton s0_12 activitym s0_dummy)
		(automaton s0_12 activityn s0_dummy)
		(automaton s0_12 activityk s0_dummy)
		(automaton s0_12 activityl s0_dummy)
		(automaton s0_12 activityq s0_dummy)
		(automaton s0_12 activityr s0_dummy)
		(automaton s0_12 activityo s0_dummy)
		(automaton s0_12 activityp s0_dummy)
		(automaton s0_12 activitys s0_dummy)
		(automaton s0_12 activityt s0_dummy)


		;DECLARE automata:
		;response(activityg,activityp)
		(cur_state s10)
		(init_state s10)
		(dummy_state s12)
		(final_state s10)
		(final_state s12)
		(automaton s10 activityg s11)
		(automaton s11 activityp s10)
		(automaton s10 response_activityg_activityp s12)
		(automaton s11 response_activityg_activityp s12)

		;precedence(activityf,activityo)
		(cur_state s20)
		(init_state s20)
		(dummy_state s23)
		(final_state s20)
		(final_state s21)
		(final_state s23)
		(automaton s20 activityf s21)
		(automaton s20 activityo s22)
		(automaton s20 precedence_activityf_activityo s23)
		(automaton s21 precedence_activityf_activityo s23)
		(automaton s22 precedence_activityf_activityo s23)

		;absence(activityk)
		(cur_state s40)
		(init_state s40)
		(dummy_state s42)
		(final_state s40)
		(final_state s42)
		(automaton s40 activityk s41)
		(automaton s40 absence_activityk s42)
		(automaton s41 absence_activityk s42)

		;existence(activityb)
		(cur_state s60)
		(init_state s60)
		(dummy_state s62)
		(final_state s61)
		(final_state s62)
		(automaton s60 activityb s61)
		(automaton s60 existence_activityb s62)
		(automaton s61 existence_activityb s62)

		;response(activityn,activityt)
		(cur_state s70)
		(init_state s70)
		(dummy_state s72)
		(final_state s70)
		(final_state s72)
		(automaton s70 activityn s71)
		(automaton s71 activityt s70)
		(automaton s70 response_activityn_activityt s72)
		(automaton s71 response_activityn_activityt s72)

	)
	(:goal (forall (?s - state) (imply (cur_state ?s) (final_state ?s))))
	(:metric minimize (total-cost))
)