package org.framedinterface.utils;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.time.Duration;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.framedinterface.model.DeclareModel;

/**
 * Turns an ENHSP plan (for a problem generated by the data-aware PDDL generator) into a replayable trace: one "action;activity" step per
 * plan event, as used by the models' updateMonitoringStates methods, plus the attribute values of each step.
 *
 * Plan actions are condensed as follows:
 *   validate-payload + sync-actions t<i> t<i+1> a                 -> "sync;<prefix event i>" (the prefix event replayed as is, with its own attribute values)
 *   skip-unused t<i> a t<i+1>                                    -> "skip;<prefix event i>" (a prefix event that no automaton knows)
 *   add_action a, add_parameter a p v..., check_added_parameter_model a, add_move_automata a
 *                                                                -> "add;<activity a>" (an event added by the planner, with attribute values p=v)
 *   reset c                                                      -> "reset constraint;<reset target of c>" (constraint c was violated and is reset)
 * Every step also gets a "timestamp" attribute: the plan's time (see HOURS_PER_PLAN_TIME_UNIT) added to the trace's start time; prefix events keep their own.
 */
public class EnhspPlanParser {

	public static final String SYNC_ACTION = "sync";
	public static final String SKIP_ACTION = "skip";
	public static final String ADD_ACTION = "add";

	private static final String TIMESTAMP_ATTRIBUTE = "timestamp";
	private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss"); //Same format as the Data-Aware page's "timestamp" attribute
	private static final Pattern STEP_PATTERN = Pattern.compile("^\\s*(\\d+(?:\\.\\d+)?):\\s*\\((.*)\\)\\s*$"); //e.g. "19.0: (sync-actions t1 t2 a2)"; "-----waiting----" lines don't match
	private static final Pattern METRIC_PATTERN = Pattern.compile("^Metric \\(Search\\):\\s*(\\S+)");
	//The generator encodes event times in hours, but the domain's "waiting" process only advances them by 0.1 per unit of plan time, so plan time 20.0 = 2 hours
	private static final double HOURS_PER_PLAN_TIME_UNIT = 0.1;

	public static class ParsedPlan {
		private boolean solved;
		private String cost = "";
		private List<String> steps = new ArrayList<String>();
		private List<Map<String, String>> attributeValues = new ArrayList<Map<String, String>>(); //Parallel to steps
		private List<Integer> prefixEventSteps = new ArrayList<Integer>(); //Prefix event (0-based) -> the (1-based) step that replayed it, or -1

		public boolean isSolved() {
			return solved;
		}
		public String getCost() {
			return cost;
		}
		public List<String> getSteps() {
			return steps;
		}
		public List<Map<String, String>> getAttributeValues() {
			return attributeValues;
		}
		public List<Integer> getPrefixEventSteps() {
			return prefixEventSteps;
		}
	}

	private Map<String, String> activityNames = new HashMap<String, String>(); //Activity encoding (e.g. "a10") -> activity name
	private Map<String, String> variableValues = new HashMap<String, String>(); //Value encoding (e.g. "integer550") -> value (e.g. "55")
	private Set<String> categoricalAttributes; //Lowercased; their value encodings are the categorical values themselves
	private Map<String, String> resetTargets; //Lowercased PDDL constraint name -> the activity a reset step should carry (default: the name itself)

	/**
	 * @param outputFolder the generator's output folder, holding its activity mapping files (activityMappingFilePattern)
	 * @param variableValuesFile the generator's value encodings (e.g. "integer550 55")
	 * @param categoricalAttributes lowercased names of categorical attributes, whose value encodings are used as is
	 * @param resetTargets lowercased PDDL constraint name -> activity for its reset steps (e.g. a Petri net's reset activity)
	 */
	public EnhspPlanParser(File outputFolder, File variableValuesFile, String activityMappingFilePattern, Set<String> categoricalAttributes, Map<String, String> resetTargets) throws IOException {
		this.categoricalAttributes = categoricalAttributes;
		this.resetTargets = resetTargets;

		File[] mappingFiles = outputFolder.listFiles((dir, name) -> name.matches(activityMappingFilePattern));
		if (mappingFiles != null) {
			for (File mappingFile : mappingFiles) {
				for (String line : readLines(mappingFile)) {
					int separator = line.lastIndexOf(':'); //e.g. "ActivityG:a10"
					if (separator > 0) {
						activityNames.putIfAbsent(line.substring(separator + 1).trim(), line.substring(0, separator).trim());
					}
				}
			}
		}

		if (variableValuesFile.isFile()) {
			for (String line : readLines(variableValuesFile)) {
				String[] parts = line.trim().split("\\s+"); //e.g. "integer550 55"
				if (parts.length == 2) {
					variableValues.put(parts[0], parts[1]);
				}
			}
		}
	}

	/**
	 * @param prefixEvents the prefix the plan was generated for (trace state t<i> is right before prefix event i)
	 * @param prefixAttributeValues the prefix's attribute values, keyed by (1-based) event number
	 * @param startTime the time the plan's time offsets are relative to (the prefix's first event, as exported)
	 */
	public ParsedPlan parse(File planFile, List<String> prefixEvents, Map<Integer, Map<String, String>> prefixAttributeValues, ZonedDateTime startTime) throws IOException {
		ParsedPlan plan = new ParsedPlan();
		for (int i = 0; i < prefixEvents.size(); i++) {
			plan.prefixEventSteps.add(-1);
		}

		boolean inPlan = false;
		String pendingAddActivity = null; //Set between add_action and add_move_automata
		Map<String, String> pendingAddValues = null;

		for (String line : readLines(planFile)) {
			if (line.startsWith("Problem Solved")) {
				plan.solved = true;
			} else if (line.startsWith("Found Plan:")) {
				inPlan = true;
			} else if (inPlan && (line.isBlank() || line.startsWith("Plan-Length"))) {
				inPlan = false;
			} else if (inPlan) {
				Matcher stepMatcher = STEP_PATTERN.matcher(line);
				if (!stepMatcher.matches()) {
					continue;
				}
				double hours = Double.parseDouble(stepMatcher.group(1)) * HOURS_PER_PLAN_TIME_UNIT;
				String timestamp = startTime.plus(Duration.ofSeconds(Math.round(hours * 3600))).format(TIMESTAMP_FORMATTER);
				String[] action = stepMatcher.group(2).trim().split("\\s+");

				switch (action[0]) {
				case "sync-actions": //(sync-actions t<i> t<i+1> a)
				case "skip-unused": //(skip-unused t<i> a t<i+1>)
					int prefixIndex = parseTraceState(action[1]);
					boolean isSync = action[0].equals("sync-actions");
					String activity = prefixIndex >= 0 && prefixIndex < prefixEvents.size() ? prefixEvents.get(prefixIndex) : decodeActivity(isSync ? action[3] : action[2]);
					Map<String, String> values = new LinkedHashMap<String, String>(prefixAttributeValues.getOrDefault(prefixIndex + 1, Collections.emptyMap()));
					values.putIfAbsent(TIMESTAMP_ATTRIBUTE, timestamp);
					addStep(plan, isSync ? SYNC_ACTION : SKIP_ACTION, activity, values);
					if (prefixIndex >= 0 && prefixIndex < prefixEvents.size()) {
						plan.prefixEventSteps.set(prefixIndex, plan.steps.size());
					}
					break;
				case "add_action": //(add_action a)
					pendingAddActivity = decodeActivity(action[1]);
					pendingAddValues = new LinkedHashMap<String, String>();
					break;
				case "add_parameter": //(add_parameter a p v)
					if (pendingAddValues != null && action.length >= 4) {
						pendingAddValues.put(action[2].toLowerCase(), decodeValue(action[2], action[3]));
					}
					break;
				case "add_move_automata": //(add_move_automata a) - completes the added event
					if (pendingAddActivity != null) {
						pendingAddValues.put(TIMESTAMP_ATTRIBUTE, timestamp);
						addStep(plan, ADD_ACTION, pendingAddActivity, pendingAddValues);
						pendingAddActivity = null;
						pendingAddValues = null;
					}
					break;
				case "reset": //(reset c)
					Map<String, String> resetValues = new LinkedHashMap<String, String>();
					resetValues.put(TIMESTAMP_ATTRIBUTE, timestamp);
					addStep(plan, DeclareModel.RESET_CONSTRAINT_ACTION, resetTargets.getOrDefault(action[1].toLowerCase(), action[1]), resetValues);
					break;
				default: //validate-payload, check_added_parameter_model and validate-failure carry no information needed for the replay
					break;
				}
			} else {
				Matcher metricMatcher = METRIC_PATTERN.matcher(line);
				if (metricMatcher.find()) {
					plan.cost = formatCost(metricMatcher.group(1));
					break; //The metric follows the plan; only the first plan in the file is used (benchmark runs may append several)
				}
			}
		}
		return plan;
	}

	private static void addStep(ParsedPlan plan, String action, String activity, Map<String, String> attributeValues) {
		plan.steps.add(action + ";" + activity);
		plan.attributeValues.add(attributeValues);
	}

	private String decodeActivity(String encoding) {
		return activityNames.getOrDefault(encoding, encoding);
	}

	private String decodeValue(String attribute, String valueEncoding) {
		if (categoricalAttributes.contains(attribute.toLowerCase())) {
			return valueEncoding; //variable_values.txt holds an index for categorical values, the encoding is the value itself
		}
		return variableValues.getOrDefault(valueEncoding, valueEncoding);
	}

	//"t3" -> 3, or -1 if unparseable
	private static int parseTraceState(String traceState) {
		try {
			return Integer.parseInt(traceState.substring(1));
		} catch (RuntimeException e) {
			return -1;
		}
	}

	//"4061.0" -> "4061"
	private static String formatCost(String cost) {
		return cost.endsWith(".0") ? cost.substring(0, cost.length() - 2) : cost;
	}

	private static List<String> readLines(File file) throws IOException {
		return List.of(new String(Files.readAllBytes(file.toPath())).split("\\R"));
	}
}
